config/routes.rb
Rails.application.routes.draw do
  resources :lecturers
  resources :sessions
  resources :surveys

  root 'static_pages#home'
  get ':page', to: 'static_pages#show', as: 'pages'

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/lecturer.rb
class Lecturer < ApplicationRecord
  has_many :teachings
  has_many :sessions, through: :teachings
  
  validates :name, presence: true
end

app/models/session.rb
class Session < ApplicationRecord
  has_many :teachings
  has_many :lecturers, through: :teachings
  has_many :surveys
  
 validates :title, presence: true
 validates :date, presence: true
 validates :lecturers, presence:true
 
 validate :date_cannot_be_in_the_future
 
  def date_cannot_be_in_the_future
    if date.present? && date > Date.today
      errors.add(:date, "can't be in the future")
    end
  end  
end  

app/models/survey.rb
class Survey < ApplicationRecord
  belongs_to :session
end

app/models/teaching.rb
class Teaching < ApplicationRecord
  belongs_to :session
  belongs_to :lecturer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/lecturers_controller.rb
class LecturersController < ApplicationController
    before_action :set_lecturer, only: [:show, :edit, :update, :destroy]
    
  def new
    @lecturer = Lecturer.new
    @lecturers = Lecturer.all
  end
  
  def create 
    @lecturers = Lecturer.all
    @lecturer = Lecturer.new(lecturer_params)
    respond_to do |format|
      if @lecturer.save
        format.html { flash[:notice] = 'Lecturer was successfully created.' and redirect_to action: "new" }
        format.json { render :new, status: :created, location: @lecturer }
      else
        format.html { render :new }
        format.json { render json: @lecturer.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def show
  end
  
  def update
    respond_to do |format|
      if @lecturer.update(lecturer_params)
        format.html { flash[:notice] = 'Lecturer name was successfully updated.' and redirect_to action: "new"}
        format.json { render :show, status: :ok, location: @lecturer }
      else
        format.html { render :edit }
        format.json { render json: @lecturer.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @lecturer.destroy
    respond_to do |format|
      format.html  { flash[:notice] = 'Lecturer was deleted.' and redirect_to new_lecturer_path }
      format.json { head :no_content }
    end
  end
  
  private
  
  # Use callbacks to share common setup or constraints between actions.
    def set_lecturer
      @lecturer = Lecturer.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def lecturer_params
      params.require(:lecturer).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    before_action :set_session, only: [:show, :edit, :update, :destroy]
  
  def index
    @sessions = Session.all
  end
  
  def show
  end
  
  def new
    @session = Session.new
    @sessions = Session.all
  end
  
  def create 
    @session = Session.new(session_params)
    respond_to do |format|
      if @session.save
        format.html { flash[:notice] = 'Session was successfully created.' and redirect_to action: "index" }
        format.json { render :index, status: :created, location: @session }
      else
        format.html { render :new }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def update
    respond_to do |format|
      if @session.update(session_params)
        format.html { flash[:notice] = 'Session was successfully updated.' and redirect_to action: "index" }
        format.json { render :show, status: :ok, location: @session }
      else
        format.html { render :edit }
        format.json { render json: @session.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def destroy
    @session.destroy
    respond_to do |format|
      format.html  { flash[:notice] = 'Session was deleted.' and redirect_to action: "index" }
      format.json { head :no_content }
    end
  end
  
  private
  
  # Use callbacks to share common setup or constraints between actions.
    def set_session
      @session = Session.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def session_params
      params.require(:session).permit(:title, :date, lecturer_ids: [])
    end
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :page
  
  def show
    render page
  end
  
  private
  
  def page
    params.has_key?(:page) ? 
    page = 'static_pages/' + params[:page] : 
    page = 'static_pages/show'
  end   
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: [:destroy]
  before_action :get_sessionid, only: [:destroy]
  
  def new
    @session= Session.find(params[:id])
    @survey = @session.surveys.build
    @surveys = Survey.all
  end
  
  def create
     @session= Session.find(params[:id])
     @survey = @session.surveys.build(survey_params)
     if @survey.save
       redirect_to new_survey_path(:id => @session.id)
     end
  end
  
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html  { flash[:notice] = 'Survey was deleted.' and redirect_to new_survey_path(:id => @sessionid)}
      format.json { head :no_content }
    end
  end
  
  
  private
  
    def set_survey
      @survey = Survey.find(params[:id])
    end
    
    def survey_params
      params.require(:survey).permit(:rating, :session_id)
    end
    
    def get_sessionid
      @sessionid = @survey.session_id
    end

    
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lecturers_helper.rb
module LecturersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
<div class="row">
  <div class="small-12 large-12 columns">
    <nav>
      <div class="menu-centered">
        <ul class="dropdown menu" data-dropdown-menu>
          <li><%= link_to 'Home', root_url %>
          <li><%= link_to 'About us', pages_path('aboutus') %></li>
          <li><%= link_to 'Lecturers', new_lecturer_path %></li>
          <li>
            <a href="#"><%= 'Sessions' %></a>
            <ul class="menu">
              <li><%= link_to 'Add a new session', new_session_path %></li>
              <li><%= link_to 'View all sessions', sessions_path %></li>
            </ul>
          </li>
        </ul>    
      </div>
    </nav>
  </div>
  <%= yield %>
</div>  
</body>

</html>

app/views/lecturers/_form.html.erb
<%= form_for(lecturer) do |f| %>
  <% if lecturer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecturer.errors.count, "error") %> prohibited this lecturer from being saved:</h2>

      <ul>
      <% lecturer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_area :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<hr>

app/views/lecturers/edit.html.erb
<h1>Editing Lecturer</h1>

<%= render 'form', lecturer: @lecturer %>

app/views/lecturers/new.html.erb
<% content_for :title, "New Lecturer" %>
<h1>Enter new lecturer information:</h1>

<%= render 'form', lecturer: @lecturer %>

List of all lecturers <br />
<% if !@lecturer.blank? %>
  <table border = 1>
    <tr>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
   <% @lecturers.each do |lecturer| %>
    <tr>
      <td><%= lecturer.name %></td>
       <td><%= link_to 'Edit', edit_lecturer_path(lecturer) %></td>
      <td><%= link_to 'Delete Lecturer', lecturer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>  
    <% end %>
    </table>
  <% else %>
  No Lecturers Entered Yet
<% end %>  

app/views/static_pages/aboutus.html.erb
<% content_for :title, "About us" %>
<h1>About Us</h1>
<p>A system that allows you to record sessions and allows participants to rate them</p>
<p>Before recording the information about sessions, you must first enter the names of all of the teaching staff in the
<%= link_to 'Lecturers', new_lecturer_path %> form.</p>
<p>After that enter the details (title and date) of the sessions taught in the 
<%= link_to 'New Sessions', new_session_path %> form.</p>
<p>After entering the session details, the sessions can be rated.</p>

app/views/static_pages/home.html.erb
<% content_for :title, "Welcome to Super Surveys" %>
<h1>Super Surveys</h1>
<p>Welcome to Survey System</p>

app/views/surveys/new.html.erb
Session: <%= @session.title %>, Date:<%= @session.date %>  (<%= link_to "back", sessions_path %>)<br>
Lecturers:
<% @session.lecturers.each do |lecturer| %> 
<%= lecturer.name %> ,
<% end %>
<hr />
<%= form_for @survey, :url => {:action => :create, :id => @session.id} do |f| -%>
   
      <%= f.radio_button :rating, 1, :onclick => "this.form.submit();" %> 1 
      <%= f.radio_button :rating, 2, :onclick => "this.form.submit();" %> 2
      <%= f.radio_button :rating, 3, :onclick => "this.form.submit();" %> 3
      <%= f.radio_button :rating, 4, :onclick => "this.form.submit();" %> 4
      <%= f.radio_button :rating, 5, :onclick => "this.form.submit();" %> 5
<% end -%>
<hr />
<% if @session.surveys.exists? %>
   <table border = 1>
      <tr>
         <th>Session Ratings</th>
         <th colspan="1"></th>
      </tr>
 <% @session.surveys.each do |survey| %>
      <% if !survey.rating.nil? %>
         <tr>
            <td><%= survey.rating %></td>
             <td><%= link_to 'Delete survey', survey, method: :delete, data: { confirm: 'Are you sure?' } %></td>
         </tr>
      <% end %>   
   <% end %>
   </table>
<% else %>
No surveys yet
<% end %>
     
   